# Generated by Django 3.0.5 on 2020-08-14 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderList',
        ),
    ]
