# Generated by Django 3.0.5 on 2020-08-15 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderList',
        ),
    ]
