# Generated by Django 3.0.5 on 2020-08-15 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderList',
        ),
    ]
